// Generated by https://quicktype.io

export interface BaseActivity {
  _id:                 string;
  activity:            string;
  activity_type:       string;
  ticket_description:  string;
  admin_activity:      string;
  fault_type:          string;
  fault_category:      string;
  problem_description: string[];
  failure_reason:      string;
  device_name:         string;
  solution_type:       string;
  tools:               string;
  supplies:            string;
  party_name:          string;
  party_description:   string;
  observations:        string;
}
